### ISSUE TITLE
md5.c:132: possible bad call to memset ?

### ISSUE THREAD

**Issue by dcb314** [cherokee/webserver#1148]
md5.c:132:23: warning: argument to 'sizeof' in 'memset' call is the same expression as the destination; did you mean to dereference it? [-Wsizeof-pointer-memaccess]

Source code is

```
memset(ctx, 0, sizeof(ctx));    /* In case it's sensitive */
```

Suggest

```
memset(ctx, 0, sizeof(*ctx));    /* In case it's sensitive */
```

**Comment by SimSonic** [comment]
Is this project alive? Why not to close this issue?

**Comment by skinkie** [comment]
Why are you complaining about tickets that do not affect you?
