### ISSUE TITLE
https://github.com/cherokee/webserver/archive/v1.2.103.zip doesn't contain admin/CTK

### ISSUE THREAD

**Issue by jabbas** [cherokee/webserver#1170]
Like in the topic, the lastest, stable v1.2.103 zip file does not contain **admin/CTK** directory contents thus, the ./autogen.sh fails...

**Comment by Borkason** [comment]
We know. Unfortunatel, this is a wee bit difficult to fix. I recommend to simply clone the current repository `git clone https://github.com/cherokee/webserver.git`. It's as stable as anything else after version 1.2.103.
