### ISSUE TITLE
Website at cherokee-project.com is awefully incomplete

### ISSUE THREAD

**Issue by mvineetmenon** [cherokee/webserver#1172]
The documentation and help given at the [home page of cherokee] (http://cherokee-project.com) is incomplete and/or old and links for various links are broken.

**Comment by skinkie** [comment]
We have a separate bugtracker for the website: 

https://github.com/cherokee/cherokee.github.com/issues

**Comment by mvineetmenon** [comment]
oh. thanks skinkie.
