### ISSUE TITLE
How can I allow DELETE method?

### ISSUE THREAD

**Issue by sanjok-bless** [cherokee/webserver#1176]
I use Cherokee 1.2.101 and Ubuntu 14. I don't understand how can I allow DELETE method.
I saw issues below

https://github.com/cherokee/webserver/issues/381
https://groups.google.com/forum/#!topic/cherokee-http/wQBLvzekIAo

But I don't know where can I extend cgi libary:
CGI_LIB_INIT (cgi, http_get | http_post | http_head | head_put | 
head_delete)

Help me please.
Thanks

**Comment by skinkie** [comment]
Recompile cherokee from github. But change this line:

https://github.com/cherokee/webserver/blob/master/cherokee/handler_cgi.c#L73

**Comment by sanjok-bless** [comment]
When I recompiled cherokee, I had following error:

handler_cgi.c:73:55: error: 'head_put' undeclared here (not in a function)
 CGI_LIB_INIT (cgi, http_get | http_post | http_head | head_put | 
                                                       ^
../cherokee/plugin.h:109:4: note: in definition of macro 'PLUGIN_INFO_HANDLER_INIT'
   (methods)                                           \
    ^
handler_cgi_base.h:49:2: note: in expansion of macro 'PLUGIN_INFO_HANDLER_EASY_INIT'
  PLUGIN_INFO_HANDLER_EASY_INIT (name, (methods))
  ^
handler_cgi.c:73:1: note: in expansion of macro 'CGI_LIB_INIT'
 CGI_LIB_INIT (cgi, http_get | http_post | http_head | head_put | 
 ^
handler_cgi.c:74:1: error: 'head_delete' undeclared here (not in a function)
 head_delete);
 ^
../cherokee/plugin.h:109:4: note: in definition of macro 'PLUGIN_INFO_HANDLER_INIT'
   (methods)                                           \
    ^
handler_cgi_base.h:49:2: note: in expansion of macro 'PLUGIN_INFO_HANDLER_EASY_INIT'
  PLUGIN_INFO_HANDLER_EASY_INIT (name, (methods))
  ^
handler_cgi.c:73:1: note: in expansion of macro 'CGI_LIB_INIT'
 CGI_LIB_INIT (cgi, http_get | http_post | http_head | head_put | 
 ^
make[3]: *** [handler_cgi.lo] Error 1
make[3]: Leaving directory `/var/www/webserver/cherokee'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/var/www/webserver/cherokee'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/www/webserver'
make: *** [all] Error 2

**Comment by skinkie** [comment]
head_delete to http_delete

**Comment by sanjok-bless** [comment]
I also changed head_put to http_put, becouse I have the same error with head_put. Cherokee recompiled, but DELETE method not allowed yet.
And when I started cherokee in cherokee-admin appeared error: 

Server Launch Error
Something unexpected just happened.
ERROR: Broken installation detected

But sites which site in this server opened.
Cherokee error log is empty.

Any ideas?

**Comment by skinkie** [comment]
This typically means that something like make install failed.

Can you recompile make clean; make; make install
