### ISSUE TITLE
Redirection rewrite removes repeated slash characters.

### ISSUE THREAD

**Issue by NeonMan** [cherokee/webserver#1183]
I've created a directory rule to make a redirection though the rewritting seems to eliminate double forward slashes. For instance:

* Make a directiory rule on any vserver. For example the /s directory
* Set the "redirection" handler
* Set a rule where regex is "/(.*)" and replacement "/cgi-bin/script.sh?$1"
* request the page "my-host.com/s/http://hello.com"
* (External or internal) Redirection incorrectly resolves to "my-host.com/cgi-bin/script.sh?http:/hello.com" (notice missing forward-slash)

At present I am fixing the issue on the script side but this behaviour of the rewrite rule seems incorrect.

**Comment by skinkie** [comment]
Because the forward slash is also in you regular expression can you try:

^/(.*)$

**Comment by NeonMan** [comment]
Same thing happens. Response logged with `wget -S` Note the "Location:" header.

    --2016-04-04 00:34:31--  https://host.com/s/https://helloworld.com
    Resolving host.com (host.com)... address
    Connecting to host.com (host.com)|address|:443... connected.
    HTTP request sent, awaiting response...
      HTTP/1.1 301 Moved Permanently
      Date: Sun, 03 Apr 2016 22:34:31 GMT
      Server: Cherokee
      Location: /cgi-bin/script.sh?https:/helloworld.com
      Content-Length: 371
      Content-Type: text/html

**Comment by skinkie** [comment]
Doesn't help me to figure out where the / is lost, if it happens in the regular expression or in the redirect itself. If you could run this example with CHEROKEE_TRACE=all cherokee-worker that would most certainly show what happens. Cherokee has to be compiled with --enable-trace for that to work.

**Comment by NeonMan** [comment]
How do I run it?

I would have to do a clean build again in any case, but I am unclear on how to run this test.

**Comment by NeonMan** [comment]
Ran the example with traces and a clean build. problem persists. Logs are quite big. May I send you the logs by e-mail?

**Comment by NeonMan** [comment]
Last message for the night, the part of the thrace where the slash is 'lost' is the following:

    Host: <server-ip>:8888
    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3
    DNT: 1
    Connection: keep-alive

              buffer.c:1291 (  cherokee_buffer_unescape_uri): Prev: /s/http://hello-world.com
              server.c:2059 (   cherokee_server_get_vserver): Trying to match '<server-ip>'
              server.c:2097 (   cherokee_server_get_vserver): No VServer matched, returning 'default'
              thread.c:0279 (                 conn_set_mode): Connection mode = writing
              thread.c:1017 (    process_active_connections): Setup connection begins: request="/s/http:/hello-world.com"
              thread.c:1018 (    process_active_connections): Connection 0x7f5a4c000900 info
      |          Request: '/s/http:/hello-world.com' (24)
      | Request Original: '' (0)
      |    Web Directory: '' (0)
      |  Local Directory: '' (0)
      |         Pathinfo: '' (0)
      |         User Dir: '' (0)
      |     Query string: '' (0)
      | Query str. Orig.: '' (0)
      |             Host: '<server-ip>' (13)
      |         Redirect: '' (0)
      |     Redirect num: 0
      |        Keepalive: 0
      | Chunked-Encoding: 0
      |            Phase: Setting up connection
      |      Range start: -1
      |        Range end: -1
      |             Rate: 0
      |     Option bits:
      \_

**Comment by NeonMan** [comment]
URL normalization removes the double-slash since it is _not_ part of the query string. It is actually behaving as expected.

Workaround, use a redirection rule for full-path instead of directory and out the double-slash containing  string in the query side:

    http://host.com/s/http://hello.com
    Becomes:
    http://host.com/s?http://hello.com

In this case the double-slash is preserved.
