### ISSUE TITLE
Cherokee catches SIGTERM and kills parent

### ISSUE THREAD

**Issue by klampworks** [cherokee/webserver#1189]
If I run this shell script:

    #!/bin/sh
    /usr/sbin/cherokee -p 8080 -r .&
    while :; do sleep 1; done

And then `killall cherokee` in another terminal, the script itself will `terminate`.

[Other people have had this problem too](http://marc.info/?l=cherokee&m=130643141607806)

I think it is because if this line: https://github.com/cherokee/webserver/blob/94dcf145b4b6587e52f68e7b81542a5a9797dff2/cherokee/main.c#L518

From `man 3 kill`:
>If pid is 0, sig shall be sent to all processes (excluding an unspecified  set of  system  processes) whose process group ID is equal to the process group ID of the sender, and for which the process has permission to send a signal.

Judging by the comment `/* Kill all child */` this is not the intended behaviour and is certainly not what I expect as a user who wants my shell script to do things after Cherokee has exited. :smiley:

**Comment by skinkie** [comment]
Mmm... when did the script become a child proces of cherokee instead of /bin/sh?

**Comment by mathkn** [comment]
cherokee is a child of the script process and inherits its process group ID. Sending SIGTERM to the process group ID will kill the script process as well as all other processes started by the script.

cherokee should either create a new session and process group using `setsid()` (like in daemon mode) or explicitly kill the pid of the worker process.

**Comment by skinkie** [comment]
@mathkn would you like to contribute a fix?

**Comment by mathkn** [comment]
Yes, I will do.
The issue has been introduced in 86613ac2f53037b027ca224fc4a89f6c2b663916 and it only occurs if cherokee is not run in daemon mode.
My suggested solution "explicitly kill the pid of the worker process" has been replaced in that commit because there might be other child processes created by the cherokee spawning mechanism. Therefore, creating a new process group should fix it.

**Comment by skinkie** [comment]
Not only the workers, also the cgi processes.

**Comment by mathkn** [comment]
Yes, that's what I wanted to say. Killing the worker process is not the right solution because there might be other processes (the cgi processes you mention) started by the spawning mechanism.
