### ISSUE TITLE
openssl 1.1

### ISSUE THREAD

**Issue by skinkie** [cherokee/webserver#1195]
Cherokee doesn't have support for OpenSSL 1.1 which leads to the situation where you can't compile Cherokee. I have already make some fixes, currently testing the results.

**Comment by skinkie** [comment]
Reviews appreciated https://github.com/cherokee/webserver/tree/openssl-1.1

**Comment by danielsilverstone-ct** [comment]
A brief scan through the change looks reasonable.  I've not done a 1.0-1.1 refactor before though; so I don't know what else to look for :(

**Comment by severach** [comment]
How do we get it to compile under openssl 1.0 with 1.1 present until 1.1 support is complete? I tried `CPPFLAGS="$CPPFLAGS -I/usr/include/openssl-1.0` and `-with-libssl=/usr/lib/openssl-1.0`.

**Comment by skinkie** [comment]
openssl 1.1 support is in now, so you can use it.
