### ISSUE TITLE
libssl not available for Ubuntu 16.04

### ISSUE THREAD

**Issue by TimoFlesch** [cherokee/webserver#1276]
Hi,
I'm trying to add HTTPS support to my cherokee server but can't seem to select a SSL/TLS backend in its general settings, as the only option is "No TLS/SSL". 
Apparently, I need to install libcherokee-mod-libssl, but it doesn't seem to be available for Ubuntu 16.04.

Steps to reproduce:  
I tried adding the cherokee ppa via 
```
add-apt-repository ppa:cherokee-webserver/ppa
apt-get update
```

 but this left me with the following error:
```
E: The repository 'http://ppa.launchpad.net/cherokee-webserver/ppa/ubuntu xenial Release' does not have a Release file.    
N: Updating from such a repository can't be done securely, and is therefore disabled by default. 
```

**Comment by TimoFlesch** [comment]
Ok I solved this by manually adding the ppa for an older release
```bash
 add-apt-repository "deb http://ppa.launchpad.net/cherokee-webserver/ppa/ubuntu saucy main"
``` 
... running 
```bash
apt update
```

... and finally
```bash
apt install libcherokee-mod-libssl
```

**Comment by skinkie** [comment]
@TimoFlesch is there a reason for you to use 16. Instead of more recent releases?
