### ISSUE TITLE
Add debian/ directory and scripts

### ISSUE THREAD

**Issue by ghost** [cherokee/webserver#35]
Hey, I'd like to build a debian package from Cherokee - it doesn't seem to be in Debian testing anymore

**Comment by gituser** [comment]
hi guys.

not really a big fan of checkinstall method .. it's only suitable for specific distros..

is there any 'official' how-to of building deb packages from the source ?

i've found so far only: http://anonscm.debian.org/cgit/collab-maint/cherokee.git

is it the most up-to-date packaging scripts for debian? 
i need to build cherokee for debian wheezy (debian 7.0).

many thanks.
